# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia
os:
    - linux
    - osx
julia:
    - 0.6
    - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
    email: false
sudo: false
script:
    - git clone https://github.com/chkwon/jpor_codes.git jpor_codes
    - julia jpor_codes/test/runtests.jl travis
