---
slug: juliabook
filename: juliabook
title: Julia Programming for Operations Research
subtitle: A Primer on Computing
description: Visit <a href='http://www.chkwon.net/julia'>http://www.chkwon.net/julia</a> for preview and more information.
author: Changhyun Kwon
copyright: 2016
uuid: 9134fbed-051f-4f9f-af8a-547769830c31
pdf_preview_page_range: 1..40
epub_mobi_preview_chapter_range: 0..1
